# This is a Terraform-managed file; manual changes will be overwritten.
# see https://github.com/workloads/github-organization/blob/main/templates/workflows/markdown.yml

---

name: "Documentation: Link Checker"

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  markdown:
    name: Markdown
    runs-on: ubuntu-latest
    steps:
      # see https://github.com/actions/checkout/releases/tag/v3.5.2
      - name: Checkout Repository
        uses: "actions/checkout@v3.5.2" # v3.5.2
        with:
          fetch-depth: 1

      # see https://github.com/gaurav-nelson/github-action-markdown-link-check/releases/tag/1.0.15
      - name: Check Links in Markdown files
        uses: "gaurav-nelson/github-action-markdown-link-check@1.0.15" # 1.0.15
        with:
          check-modified-files-only: no
          config-file: ".markdown-link-check.json"
          file-extension: ".md"
          use-verbose-mode: yes
