# This is a Terraform-managed file; manual changes will be overwritten.
# see https://github.com/workloads/github-organization/blob/main/templates/workflows/markdown.tftpl.yml

---

name: "Documentation: Link Checker"

# yamllint disable-line rule:truthy
on:
  push:

# see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions: read-all

jobs:
  workflow:
    # only run if workflows are enabled
    if: ${{ vars.ENABLE_WORKFLOWS == 'true' }}

    # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
    concurrency:
      group: "${{ github.workflow }}-${{ github.ref }}"
      cancel-in-progress: true

    name: Markdown
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # see https://github.com/actions/checkout/releases/tag/v3.5.2
      - name: Checkout Repository
        uses: "actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab" # ref: `tags/v3.5.2`
        with:
          fetch-depth: 1

      # see https://github.com/gaurav-nelson/github-action-markdown-link-check/releases/tag/1.0.15
      - name: Check Links in Markdown files
        uses: "gaurav-nelson/github-action-markdown-link-check@d53a906aa6b22b8979d33bc86170567e619495ec" # ref: `tags/1.0.15`
        with:
          check-modified-files-only: no
          config-file: ".markdown-link-check.json"
          file-extension: ".md"
          use-verbose-mode: yes

  workflow-inactive:
    # only run if workflows are disabled
    if: ${{ vars.ENABLE_WORKFLOWS != 'true' }}

    name: Workflow Status
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Display Workflow Status
        run: echo "::warning ::Workflow is not currently active. Check if `ENABLE_WORKFLOWS` is set to `true`."
