---
name: "Code Quality: Super-Linter"

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  lint:
    name: super-linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Lint Code
        uses: github/super-linter@v3
        env:
          ANSIBLE_DIRECTORY: "./ansible/playbooks"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: "main"
          DISABLE_ERRORS: false
          MULTI_STATUS: true
          SUPPRESS_POSSUM: true
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_ANSIBLE: true
          VALIDATE_BASH: true
          VALIDATE_JSON: true
          VALIDATE_MD: true
          VALIDATE_TERRAFORM: true
          VALIDATE_YAML: true
