# This is a Terraform-managed file; manual changes will be overwritten.
# see https://github.com/workloads/github-organization/blob/main/templates/workflows/superlinter.yml

---
name: "Code Quality: Super-Linter"

# yamllint disable-line rule:truthy
on:
  push:

jobs:
  superlinter:
    name: Super-Linter
    runs-on: ubuntu-latest
    steps:
      # see https://github.com/actions/checkout/releases/tag/v3.5.2
      - name: Checkout Repository
        uses: "checkout@v3.5.2" # v3.5.2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      # see https://github.com/github/v5.0.0
      - name: Lint Code with Super-Linter
        uses: "super-linter@v5.0.0" # v5.0.0
        env:
          # see https://github.com/github/super-linter#environment-variables
          VALIDATE_ALL_CODEBASE: true
          CSS_FILE_NAME: ".stylelintrc.json"
          DEFAULT_BRANCH: main
          DISABLE_ERRORS: false
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MARKDOWN_CONFIG_FILE: ".markdown-lint.yml"
          MULTI_STATUS: true
          SUPPRESS_POSSUM: true
          TERRAFORM_TFLINT_CONFIG_FILE: ".tflint.hcl"
          VALIDATE_BASH: true
          VALIDATE_CSS: true
          VALIDATE_HTML: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_SHELL_SHFMT: true
          VALIDATE_TERRAFORM: true
          VALIDATE_TERRAFORM_TFLINT: true
          VALIDATE_YAML: true
